import express from "express"
import { respondWithError } from "../utilities/shared.js"
import auth0Middleware from "../auth/index.js"
import ProjectFactory from "../classes/Project/ProjectFactory.js"
import validateURL from "../utilities/validateURL.js"
import Project from "../classes/Project/Project.js"
import screenContentMiddleware from "../utilities/checkIfSuspicious.js"
import { isSuspiciousJSON } from "../utilities/checkIfSuspicious.js"
import Tools from "../classes/Tools/Tools.js"

const router = express.Router({ mergeParams: true })

/**
 * Private function to check on metadata, tools, layers, and layer.pages data of a project.
 * They may contain data generated by direct user input, such as labels. 
 * It may be malformed, but let that be caught downstream.
 *
 * @param project - The project data from the request body.  
 */
function hasSuspiciousProjectData(project) {
  // Expect that project.metadata is an Array of JSON objects.  If not the project data malformed so skip it.
  if (project.metadata && Array.isArray(project.metadata)) {
    for (const metadataObj of project.metadata) {
      if (isSuspiciousJSON(metadataObj, [], true, 1)) return true
    }
  }
  // Expect that project.layers is an Array of JSON objects.  If not the project data is malformed so skip it.
  if (project.layers && Array.isArray(project.layers)) {
    for (const layerObj of project.layers) {
      if (isSuspiciousJSON(layerObj, [], true, 1)) return true
      const pages = layerObj.pages
      // Expect that layer.pages is an Array of JSON objects.  If not the project data is malformed so skip it.
      if (Array.isArray(pages)) {
        for (const pageObj of pages) {
          if (isSuspiciousJSON(pageObj, [], true, 2)) return true
        }
      }
    }
  }
  // Expect that project.tools is an Array of JSON objects.  If not the project data is malformed so skip it.
  if (project.tools && Array.isArray(project.tools)) {
    for (const toolObj of project.tools) {
      if (isSuspiciousJSON(toolObj, [], true, 1)) return true
    }
  }
  return false
}

router.route("/create").post(auth0Middleware(), screenContentMiddleware(), async (req, res) => {
  const user = req.user
  if (!user?.agent) return respondWithError(res, 401, "Unauthenticated user")
  let project = req.body
  try {
    if (hasSuspiciousProjectData(project)) return respondWithError(res, 400, "Suspicious project data will not be processed.")
    project = { ...project, creator: user?.agent }
    const projectObj = new Project()
    const newProject = await projectObj.create(project)
    res.setHeader("Location", newProject?._id)
    res.status(201).json(newProject)
  } catch (error) {
    console.log("Project creation error")
    console.error(error)
    respondWithError(
      res,
      error.status ?? error.code ?? 500,
      error.message ?? "Unknown server error"
    )
  }
}).all((_, res) => {
  respondWithError(res, 405, "Improper request method. Use POST instead")
})

router.route("/import").post(auth0Middleware(), async (req, res) => {
  let { createFrom } = req.query
  let user = req.user
  createFrom = createFrom?.toLowerCase()
  if (!createFrom)
    return res.status(400).json({
      message:
        "Query string 'createFrom' is required, specify manifest source as 'URL' or 'DOC' "
    })
  if (createFrom === "url") {
    const manifestURL = req?.body?.url
    let tools = req?.body?.tools ?? []
    if (!Array.isArray(tools)) tools = []
    let checkURL = await validateURL(manifestURL)
    if (!checkURL.valid)
      return res.status(checkURL.status).json({
        message: checkURL.message,
        resolvedPayload: checkURL.resolvedPayload
      })
    try {
      tools = await new Tools().validateAllTools(tools)
      const result = await ProjectFactory.fromManifestURL(
        manifestURL,
        user.agent.split('/').pop(),
        tools
      )
      res.status(201).json(result)
    } catch (error) {
      res.status(error.status ?? 500).json({
        status: error.status ?? 500,
        message: error.message,
        data: error.resolvedPayload
      })
    }
  } else if (createFrom === "tpen28url") {
    const manifestURL = req?.body?.url
    let checkURL = await validateURL(manifestURL)
    if (!checkURL.valid)
      return res.status(checkURL.status).json({
        message: checkURL.message,
        resolvedPayload: checkURL.resolvedPayload
      })
    try {
      const result = await ProjectFactory.fromManifestURL(
        manifestURL,
        user.agent.split('/').pop(),
        true
      )
      res.status(201).json(result)
    } catch (error) {
      res.status(error.status ?? 500).json({
        status: error.status ?? 500,
        message: error.message,
        data: error.resolvedPayload
      })
    }
  } else {
    res.status(400).json({
      message: `Import from ${createFrom} is not available. Create from URL instead`
    })
  }
}).all((req, res) => {
  respondWithError(res, 405, "Improper request method. Use POST instead")
})

router.route("/import-image").post(auth0Middleware(), async (req, res) => {
  const user = req.user
  if (!user?.agent) return respondWithError(res, 401, "Unauthenticated user")
  try {
    const { imageUrl, projectLabel } = req.body
    if (!imageUrl || !projectLabel) {
      return respondWithError(res, 400, "Image URL and project label are required")
    }
    const project = await ProjectFactory.createManifestFromImage(imageUrl, projectLabel, user.agent.split('/').pop())
    res.status(201).json(project)
  } catch (error) {
    respondWithError(
      res,
      error.status ?? error.code ?? 500,
      error.message ?? "Unknown server error"
    )
  }
}
).all((_, res) => {
  respondWithError(res, 405, "Improper request method. Use POST instead")
})

/**
 * Free typed strings may be malicious or rude.  The key 'label' is not malicious but the value req.body.label could be.
 */
router.route("/:projectId/label").patch(auth0Middleware(), screenContentMiddleware(), async (req, res) => {
  const user = req.user
  if (!user?.agent) return respondWithError(res, 401, "Unauthenticated user")
  const projectId = req.params.projectId
  if (!projectId) return respondWithError(res, 400, "Project ID is required")
  const { label } = req.body
  if (typeof label !== "string" || !label?.trim()) return respondWithError(res, 400, "JSON with a 'label' property required in the request body.  It cannot be null or blank and must be a string.")
  try {
    let project = new Project(projectId)
    const loadedProject = await project.loadProject()
    if (!loadedProject) return respondWithError(res, 404, "Project not found")
    project = await project.setLabel(label)
    res.status(200).json(project)
  } catch (error) {
    respondWithError(
      res,
      error.status ?? error.code ?? 500,
      error.message ?? "Unknown server error"
    )
  }
}).all((_, res) => {
  respondWithError(res, 405, "Improper request method. Use PATCH instead")
})

export default router
